### ISSUE TITLE
Checking for headers_sent

### ISSUE THREAD

**Issue by thefrosty** [EthanKennedy/wpe-advanced-cache#14]
We're got a REST Api theme that shows an posts REST data. And since it's building a request during the theme build it's after headers have already been sent. The `WPEAC_CORE::send_header_cache_control_api` method should wrapper the header function in a condition to check if the headers have been sent yet to avoid errors.

```
if (!headers_sent()) {
    header("Cache-Control: max-age=$namespace_cache_length, must-revalidate");
}
```

**Comment by EthanKennedy** [comment]
Yeah that makes a lot of sense, the check should exist in `WPEAC_CORE::send_header_cache_control_api` as well. I'll add it and test to see if anything behaves oddly, if not I'll push an update.
