### ISSUE TITLE
Nginx Expire Headers

### ISSUE THREAD

**Issue by jeffmankini** [EthanKennedy/wpe-advanced-cache#20]
Hi there!

I was asked by WP Engine to reach out to the plugin developer and ask

“what the expired headers need to be set to eliminate this warning.
The current default expire headers on the site are as follows:
add_header Cache-Control “public, max-age=31536000″;”.

What I’m wanting to do is optimize my performance and SEO, and one suggestion was to include expires headers, including on images.

Rank Math Pro shows that the images still have no expires headers, even with the plugin installed and activated.

**Comment by EthanKennedy** [comment]
I think we talked about this on the plugin support page, but altering nginx headers isn't something we could easily do with this plugin.
